name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Install google test and boost, also install g++-11 for ranges
      run: sudo apt-get install libgtest-dev googletest googletest-tools google-mock libboost-dev g++-11
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: CMake Lib release config
      run: cmake -S . -B release -DCMAKE_CXX_COMPILER=g++-11 -DCMAKE_BUILD_TYPE=Release
    - name: CMake Lib release build
      run: cmake --build release
    - name: CMake Lib debug config
      run: cmake -S . -B debug -DCMAKE_CXX_COMPILER=g++-11 -DCMAKE_BUILD_TYPE=Debug
    - name: CMake Lib debug build
      run: cmake --build debug

    - name: Run tests
      run: |
        ls -l
        cd debug 
        ls -l
        ./fin_data_tests